[package]
name = "kiwi-talk-client"
version = "0.1.0"
authors = ["KiwiTalk contributors"]
license = "Apache-2.0"
repository = "https://github.com/KiwiTalk/kiwitalk"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
futures = "0.3.24"
bson = "2.4.0"

talk-loco-client = { path = "../talk-loco-client" }
talk-loco-command = { path = "../talk-loco-command" }
kiwi-talk-db = { path = "../kiwi-talk-db" }