[package]
name = "talk-loco-client"
version = "0.1.0"
license = "Apache-2.0"
keywords = ["talk", "loco"]
readme = "README.md"
description = "Loco client"
authors = ["KiwiTalk contributors"]
edition = "2021"

[dependencies]
serde = { version = "1.0" }
tokio = { version = "1", features = ["rt", "net", "sync"] }
futures = "0.3.24"
bson = "2.4.0"
rustc-hash = "1.1.0"
talk-loco-command = { path = "../talk-loco-command" }
loco-protocol = "5.1.0"
thiserror = "1.0"

[dev-dependencies]
tokio-native-tls = "0.3.0"
tokio-util = { version = "0.7.4", features = ["compat"] }
tokio = { version = "1", features = ["full"] }
